/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PofinRouteImport } from './routes/pofin'
import { Route as HyundaiRouteImport } from './routes/hyundai'
import { Route as GraduationRouteImport } from './routes/graduation'
import { Route as ClosyRouteImport } from './routes/closy'
import { Route as IndexRouteImport } from './routes/index'

const PofinRoute = PofinRouteImport.update({
  id: '/pofin',
  path: '/pofin',
  getParentRoute: () => rootRouteImport,
} as any)
const HyundaiRoute = HyundaiRouteImport.update({
  id: '/hyundai',
  path: '/hyundai',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduationRoute = GraduationRouteImport.update({
  id: '/graduation',
  path: '/graduation',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosyRoute = ClosyRouteImport.update({
  id: '/closy',
  path: '/closy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/closy': typeof ClosyRoute
  '/graduation': typeof GraduationRoute
  '/hyundai': typeof HyundaiRoute
  '/pofin': typeof PofinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/closy': typeof ClosyRoute
  '/graduation': typeof GraduationRoute
  '/hyundai': typeof HyundaiRoute
  '/pofin': typeof PofinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/closy': typeof ClosyRoute
  '/graduation': typeof GraduationRoute
  '/hyundai': typeof HyundaiRoute
  '/pofin': typeof PofinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/closy' | '/graduation' | '/hyundai' | '/pofin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/closy' | '/graduation' | '/hyundai' | '/pofin'
  id: '__root__' | '/' | '/closy' | '/graduation' | '/hyundai' | '/pofin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClosyRoute: typeof ClosyRoute
  GraduationRoute: typeof GraduationRoute
  HyundaiRoute: typeof HyundaiRoute
  PofinRoute: typeof PofinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pofin': {
      id: '/pofin'
      path: '/pofin'
      fullPath: '/pofin'
      preLoaderRoute: typeof PofinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyundai': {
      id: '/hyundai'
      path: '/hyundai'
      fullPath: '/hyundai'
      preLoaderRoute: typeof HyundaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduation': {
      id: '/graduation'
      path: '/graduation'
      fullPath: '/graduation'
      preLoaderRoute: typeof GraduationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closy': {
      id: '/closy'
      path: '/closy'
      fullPath: '/closy'
      preLoaderRoute: typeof ClosyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClosyRoute: ClosyRoute,
  GraduationRoute: GraduationRoute,
  HyundaiRoute: HyundaiRoute,
  PofinRoute: PofinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
